apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-deployment
  namespace: wbs-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
      - name: apigateway
        image: 739272173743.dkr.ecr.ap-northeast-2.amazonaws.com/wbs/apigateway:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: API_GATEWAY_SERVER_PORT
          value: "8080"
        - name: GATEWAY_ALLOWED_ORIGINS
          value: https://www.wbs.asia
        - name: GATEWAY_CONNECT_TIMEOUT_MS
          value: "3000"
        - name: GATEWAY_RESPONSE_TIMEOUT
          value: 10s
        - name: ACCOUNT_SERVICE_URI
          value: http://account-service
        - name: MASTER_SERVICE_URI
          value: http://master-service
        - name: STOCK_SERVICE_URI
          value: http://stock-service
        - name: SEARCH_SERVICE_URI
          value: http://search-service
        - name: AI_SERVICE_URI
          value: http://ai-service
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: wbs-secrets
              key: JWT_SECRET_KEY
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: apigateway-service
  namespace: wbs-ns
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: apigateway
